version: '2'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./jenkins_home:/var/jenkins_home
      - /etc/timezone:/etc/timezone
      - /etc/localtime:/etc/localtime
